repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.3
    hooks:
      - id: golangci-lint
        args: [--timeout=5m]
